name: Deploy via rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout Code
        uses: actions/checkout@v4

      - name: 🔑 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'unnecessary' # We will skip host verification for simplicity
          if_key_exists: replace

      - name: 🚀 Deploy with rsync
        run: |
          rsync -avz --delete \
          -e "ssh -p 2100 -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/public_html/panorb